[general]
appName = "AI Jurist"
favicon = "path/to/your/favicon.ico"
theme = "custom"

[theme]
primaryColor = "#37c4ff"  # Magenta
backgroundColor = "#000000"  # Dark gray background
secondaryBackgroundColor = "#141414"  # Slightly lighter gray for secondary background
textColor = "#FFFFFF"  # White text color
font = "monospace"
